# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c  
osx_image: xcode8 
xcode_workspace: Example/AHCarouselViewController.xcworkspace 
xcode_scheme: AHCarouselViewController-Example

script: 
— xcodebuild clean build -workspace Example/AHCarouselViewController.xcworkspace  -scheme AHCarouselViewController-Example -destination “platform=iOS Simulator,name=iPhone 6S”
